server:
  port: 8080

upload:
  location: /data/web/raw
  kalocation: /data/web/ka

model:
  location: /data/web/json
  skinurl: http://localhost:10000/scoring/online/skin

spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB